spring.datasource.url=jdbc:postgresql://dpg-d78b7uh4tr6s73c0ddu0-a:5432/ecotrack_db_ltyc
spring.datasource.username=ecotrack_db_ltyc_user
spring.datasource.password=eZxkJk9tzHfqAukoWZbRnrmQYnOhNXMs
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.datasource.hikari.data-source-properties.ssl=true
spring.datasource.hikari.data-source-properties.sslmode=require
